wrap_comments = true
normalize_comments = true
format_strings = true
format_macro_matchers = true
fn_single_line = false
merge_imports = false
reorder_imports = false
imports_layout = "HorizontalVertical"
edition = "2018"